name: dosiero
excludes:
    - vendor
services:
    appserver:
        type: php:8.5
        via: apache:2.4
        ssl: true
        sslExpose: true
        webroot: .
        scanner: false
        composer_version: 2-latest
        xdebug: true
        overrides:
            environment:
                XDEBUG_MODE: 'off'
        build_as_root:
            - docker-php-ext-install sockets
proxy:
    appserver:
        - dosiero-php.local
tooling:
    install:
        description: install third party packages
        cmd:
            - appserver: composer install
    php:
        service: appserver
        dir: /app
    composer:
        service: appserver
        dir: /app
    phpstan:
        service: appserver
        description: static analysis (PHPStan)
        dir: /app
        cmd: php /app/vendor/bin/phpstan analyze -c build/phpstan.neon --no-progress --error-format=raw
    phpstan-log:
        service: appserver
        description: static analysis (PHPStan) to build/reports/phpstan.txt
        dir: /app
        cmd: php /app/vendor/bin/phpstan analyze -c build/phpstan.neon --no-progress --error-format=raw > build/reports/phpstan.txt
    rector:
        service: appserver
        description: rector dry-run
        dir: /app
        cmd: php /app/vendor/bin/rector --dry-run --no-progress-bar
    rector-fix:
        service: appserver
        description: rector
        dir: /app
        cmd: php /app/vendor/bin/rector --no-progress-bar
    ecs:
        service: appserver
        description: easy coding standards
        dir: /app
        cmd: php /app/vendor/bin/ecs check --no-progress-bar
    ecs-fix:
        service: appserver
        description: easy coding standards
        dir: /app
        cmd: php /app/vendor/bin/ecs check --fix --no-progress-bar
    codeception:
        service: appserver
        description: Run codeception
        dir: /app
        cmd: /app/vendor/bin/codecept
    tests:
        service: appserver
        description: all tests (Codeception)
        dir: /app
        cmd: /app/vendor/bin/codecept run --html report-tests.html
    coverage:
        service: appserver
        description: code coverage (Codeception)
        dir: /app
        cmd: XDEBUG_MODE=coverage /app/vendor/bin/codecept run --html report-coverage.html --coverage-html --coverage-text
events:
    pre-start:
        - appserver: composer install